mynewtestproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),  # Include URLs from the users app
    path('students/', include('students.urls')),  # Include URLs from the Students app
    path('staff/', include('staff.urls')),  # Include URLs from the Staff app
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('profile/create/', views.create_profile, name='create_profile'),
    path('profile/view/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('choose_assignment_type/', views.choose_assignment_type, name='choose_assignment_type'),
    path('create_assignment/', views.create_assignment, name='create_assignment'),
    path('view_submissions/', views.view_submissions, name='view_submissions'),
    path('grade_submission/<int:submission_id>/', views.grade_submission, name='grade_submission'),
    path('assigned-courses/', views.view_assigned_courses, name='view_assigned_courses'),
    path('create-quiz/', views.create_quiz, name='create_quiz'),
    path('add_questions/<int:assignment_id>/', views.add_questions, name='add_questions'),
    path("quizzes/", views.list_quizzes, name="list_quizzes"),
    path("quizzes/<int:quiz_id>/add-questions/", views.add_questions_to_quiz, name="add_questions_to_quiz"),

]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('profile/create/', views.create_profile, name='create_profile'),
    path('profile/view/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('dashboard/', views.student_dashboard, name='student_dashboard'),
    path('enroll/', views.enroll_course, name='enroll_course'),  # New URL for course enrollment
    path('my_courses/', views.my_courses, name='my_courses'),  # New URL for viewing enrolled courses
    path('grades/', views.view_grades, name='view_grades'),  # New URL for viewing grades
    path('assignments/', views.my_assignments, name='my_assignments'),  # New URL for viewing assignments
    path('assignments/<int:assignment_id>/', views.assignment_detail, name='assignment_detail'),  # New URL for viewing a specific assignment
    path('assignments/<int:assignment_id>/submit/', views.submit_assignment, name='submit_assignment'),  # New URL for submitting an assignment
    path('assignments/submissions/', views.my_submissions, name='my_submissions'),  # New URL for viewing submissions
    path('quiz/<int:assignment_id>/', views.take_quiz, name='take_quiz'),
    path('quiz/<int:assignment_id>/result/', views.quiz_result, name='quiz_result'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'users'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path("admin_dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("staff_dashboard/", views.staff_dashboard, name="staff_dashboard"),
    path("student_dashboard/", views.student_dashboard, name="student_dashboard"),
]

students/models.py
# Create your models here.
from django.db import models
from django.conf import settings

class StudentProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="student_profile"
    )
    admission_number = models.CharField(max_length=30, unique=True)
    date_of_birth = models.DateField(null=True, blank=True)
    course = models.CharField(max_length=100, blank=True)
    year_of_study = models.IntegerField(default=1)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(
        upload_to='profile_pics/', default='profile_pics/default.jpg'
    )

    def __str__(self):
        return f"{self.user.username} - {self.admission_number}"
    
#COURSE ENROLLMENT
class Course(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    instructor = models.ForeignKey(
        settings.AUTH_USER_MODEL,   # links to your CustomUser
        on_delete=models.SET_NULL,
        null=True, blank=True) # only staff can be chosen

    def __str__(self):
        return f"{self.code} - {self.name}"


class Enrollment(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, limit_choices_to={'user_type': 'student'})
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    enrolled_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('student', 'course')  # avoid duplicates

    def __str__(self):
        return f"{self.student.username} enrolled in {self.course.code}"


class Grade(models.Model):
    enrollment = models.ForeignKey('Enrollment', on_delete=models.CASCADE, related_name='grades')
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    score = models.DecimalField(max_digits=5, decimal_places=2)  # e.g. 89.50
    grade = models.CharField(max_length=2)  # e.g. A, B, C
    feedback = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.enrollment.student.username} - {self.course.code} : {self.grade}"

#ASSIGNMENT AND SUBMISSION MODELS
class Assignment(models.Model):
    ASSIGNMENT_TYPES =[
        ("FILE", "File Upload"),
        ("QUIZ", "Interactive Quiz"),#NEW
    ]
    course = models.ForeignKey("students.Course", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    due_date = models.DateTimeField()
    assignment_type = models.CharField(max_length=10, choices=ASSIGNMENT_TYPES, default="FILE")#NEW
    file = models.FileField(upload_to='assignments/', null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.SET_NULL, 
        null=True,
        
    )

    def __str__(self):
        return f"{self.title} - {self.course.name}"


class Submission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                limit_choices_to={'user_type': 'student'})
    file = models.FileField(upload_to='submissions/')
    submitted_at = models.DateTimeField(auto_now_add=True)
    grade = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    feedback = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.assignment.title} by {self.student.username}"

#QUESTION BANK MODELS
class Question(models.Model):
    QUESTION_TYPES = [
        ("MCQ", "Multiple Choice"),
        ("TEXT", "Short Answer"),
    ]
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name="questions")
    text = models.TextField()
    question_type = models.CharField(max_length=10, choices=QUESTION_TYPES)
    # For MCQs
    option_a = models.CharField(max_length=255, blank=True, null=True)
    option_b = models.CharField(max_length=255, blank=True, null=True)
    option_c = models.CharField(max_length=255, blank=True, null=True)
    option_d = models.CharField(max_length=255, blank=True, null=True)
    correct_answer = models.CharField(max_length=255, blank=True, null=True)
    answer_text = models.TextField(blank=True, null=True)  # For TEXT questions



class StudentResponse(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.TextField(null=True, blank=True)   # for text questions
    selected_choice = models.CharField(max_length=1, null=True, blank=True)  # for MCQ
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Response by {self.student.username} for Question {self.question.id}"
 

students/forms.py
from django import forms
from .models import StudentProfile, Enrollment, Course, Submission

class StudentProfileForm(forms.ModelForm):
    class Meta:
        model = StudentProfile
        fields = ['admission_number', 'date_of_birth', 'course', 'year_of_study', 'bio', 'profile_picture']


class EnrollmentForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        fields = ['course']

class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ['file']

students/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import StudentProfileForm, EnrollmentForm, SubmissionForm
from .models import StudentProfile, Enrollment, Course, Grade, Assignment, Submission, StudentResponse, Question
from users.views import is_student  # Add this import from users app

@login_required
@user_passes_test(is_student)
def student_dashboard(request):
    return render(request, 'users/student_dashboard.html') 


@login_required
def create_profile(request):
    if hasattr(request.user, 'student_profile'):
        return redirect('students:view_profile')  # Prevent duplicate profile

    if request.method == 'POST':
        form = StudentProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('students:view_profile')
    else:
        form = StudentProfileForm()
    return render(request, 'students/create_profile.html', {'form': form})

@login_required
def view_profile(request):
    profile = get_object_or_404(StudentProfile, user=request.user)
    return render(request, 'students/view_profile.html', {'profile': profile})

@login_required
def edit_profile(request):
    profile = get_object_or_404(StudentProfile, user=request.user)
    if request.method == 'POST':
        form = StudentProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('students:view_profile')
    else:
        form = StudentProfileForm(instance=profile)
    return render(request, 'students/edit_profile.html', {'form': form})


@login_required
@user_passes_test(is_student)
def enroll_course(request):
    courses = Course.objects.all()
    if request.method == "POST":
        course_ids = request.POST.getlist('courses')
        for course_id in course_ids:
            course = Course.objects.get(id=course_id)
            Enrollment.objects.get_or_create(student=request.user, course=course)
        return redirect("students:my_courses")
    return render(request, "students/enroll_course.html", {"courses": courses})
        
@login_required
def my_courses(request):
    enrollments = Enrollment.objects.filter(student=request.user)
    return render(request, 'students/my_courses.html', {'enrollments': enrollments})

@login_required
@user_passes_test(is_student)
def view_grades(request):
    grades = Grade.objects.filter(enrollment__student=request.user)
    return render(request, "students/view_grades.html", {"grades": grades})

#ASSIGNMENTS AND SUBMISSION VIEWS
# View all assignments for enrolled courses
@login_required
@user_passes_test(is_student)
def my_assignments(request): 
    # fetch enrollments for the student
    enrollments = Enrollment.objects.filter(student=request.user)
    # fetch courses the student is enrolled in
    enrolled_courses = [enrollment.course for enrollment in enrollments]
    # fetch assignments for those courses
    assignments = Assignment.objects.all()
    #assignments = Assignment.objects.filter(course__in=enrolled_courses)
    return render(request, "students/my_assignments.html", {"assignments": assignments})


# View a single assignment (details)
@login_required
@user_passes_test(is_student)
def assignment_detail(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    questions = assignment.questions.all()  # Fetch all questions linked to the assignment
    return render(request, "students/assignment_detail.html", {"assignment": assignment, "questions": questions})

 #Submit an assignment
@login_required
@user_passes_test(is_student)
def submit_assignment(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)

    if request.method == "POST":
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.assignment = assignment
            submission.student = request.user
            submission.save()
            return redirect("students:my_assignments")
    else:
        form = SubmissionForm()

    return render(request, "students/submit_assignment.html", {"form": form, "assignment": assignment})


# View my submissions (with grades if available)
@login_required
@user_passes_test(is_student)
def my_submissions(request):
    submissions = Submission.objects.filter(student=request.user)
    return render(request, "students/my_submissions.html", {"submissions": submissions})

#INTERACTIVE ASSESMENT ENGINE VIEWS
@login_required
@user_passes_test(is_student)
def take_quiz(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id, assignment_type="QUIZ")
    questions = assignment.questions.all()
    # Debugging: Print questions to the console
    print(f"Questions for assignment {assignment_id}: {questions}")

    if request.method == "POST":
        #score = 0
        #total = questions.count()
        # Process each question's answer
        for question in questions:
            user_answer = request.POST.get(f"question_{question.id}")
            if question.question_type == "MCQ":
                #SAVE SELECTED CHOICE
                user_answer = user_answer.upper() if user_answer else None
                StudentResponse.objects.create(
                    student=request.user,
                    question=question,
                    selected_choice=user_answer
                )
                #if user_answer == question.correct_answer:
                    #score += 1

            elif question.question_type == "TEXT":
                    StudentResponse.objects.create(
                        student=request.user,
                        question=question,
                        answer_text=user_answer
                    )
        return redirect('students:quiz_result', assignment_id=assignment.id)
    return render(request, "students/take_quiz.html", {"assignment": assignment, "questions": questions})

@login_required
@user_passes_test(is_student)
def quiz_result(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id, assignment_type="QUIZ")
    questions = assignment.questions.all()
    responses = StudentResponse.objects.filter(student=request.user, question__in=questions)
    score = 0
    total = questions.count()
    for question in questions:
        if question.question_type == "MCQ":
            response = responses.filter(question=question).first()
            if response and response.selected_choice:
                # Compare the selected choice with the correct answer
                if response.selected_choice == question.correct_answer:
                   score += 1
        
        elif question.question_type == "TEXT":
            response = responses.filter(question=question).first()
            if response and response.answer_text:
                # Compare the submitted answer with the correct answer
                if response.answer_text.strip().lower() == question.answer_text.strip().lower():
                    score += 1  # Increment score for correct TEXT answers

    return render(request, "students/quiz_result.html", {
        "assignment": assignment,
        "score": score,
        "total": total,
        "responses": responses,
        "questions": questions,
    })

students/templates/students/assignment_detail.html
<h2>{{ assignment.title }}</h2>
<p>Course: {{ assignment.course.name }}</p>
<p>{{ assignment.description }}</p>
<p>Due: {{ assignment.due_date }}</p>
{% if assignment.assignment_type == "QUIZ" %}
  <h3>Questions:</h3>
  <ul>
    {% for question in questions %}
      <li>{{ question.text }}</li>
    {% empty %}
      <p>No questions added yet.</p>
    {% endfor %}
  </ul>
{% endif %}
{% if assignment.file %}
<a href="{{ assignment.file.url }}">Download Assignment File</a>
{% endif %} 
<br>
<a href="{% url 'students:submit_assignment' assignment.id %}">Submit Assignment</a>
<br>
<a href="{% url 'students:my_assignments' %}">Back to My Assignments</a>

students/templates/students/create_profile.html
<h2>Create Profile</h2>
<form method="post" enctype="multipart/form-data"> <!-- enctype added -->
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

students/templates/students/edit_profile.html
<h2>Edit Profile</h2>
<form method="post" enctype="multipart/form-data"> <!-- enctype added -->
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

students/templates/students/enroll_course.html
{% block content %}
<h2>Enroll in a Course</h2>
<form method="post">
  {% csrf_token %}
  <label for="course">Select a course:</label>
    <select name="courses" id="courses" multiple required>
        {% for course in courses %}
            <option value="{{ course.id }}">{{ course.name }} ({{ course.code }})</option>
        {% endfor %}
    </select>
    <button type="submit">Enroll</button>
</form>
{% endblock %}

students/templates/students/my_assignments.html
<h2>My Assignments</h2>
<ul>
  {% for assignment in assignments %}
    <li>
      <a href="{% url 'students:assignment_detail' assignment.id %}">
        {{ assignment.title }} - {{ assignment.course.name }} (Due: {{ assignment.due_date }})
        {% if assignment.assignment_type == "QUIZ" %}
      <a href="{% url 'students:take_quiz' assignment.id %}">Take Quiz</a>
    {% endif %}
      </a>
    </li>
  {% empty %}
    <p>No assignments yet.</p>
  {% endfor %}
</ul>

students/templates/students/my_courses.html
{% block content %}
<h2>My Courses</h2>

<ul>
  {% for enrollment in enrollments %}
    <li>{{ enrollment.course.name }} - {{ enrollment.course.code }}</li>
  {% empty %}
    <li>You are not enrolled in any courses yet.</li>
  {% endfor %}
</ul>
{% endblock %}

students/templates/students/my_submissions.html
<h2>My Submissions</h2>
<ul>
  {% for submission in submissions %}
    <li>
      {{ submission.assignment.title }} -
      Submitted on: {{ submission.submitted_at }} -
      {% if submission.grade %}
        Grade: {{ submission.grade }}
      {% else %}
        Not graded yet
      {% endif %}
    </li>
  {% empty %}
    <p>No submissions yet.</p>
  {% endfor %}
</ul>
<a href="{% url 'students:my_assignments' %}">Back to My Assignments</a>

students/templates/students/quiz_result.html
<h2>Quiz Result: {{ assignment.title }}</h2>
<p>Your Score: {{ score }} out of {{ total }}</p>
<ul>
  {% for question in questions %}
    <li>
      <strong>{{ question.text }}</strong><br>
      {% for response in responses %}
        {% if response.question.id == question.id %}
          {% if question.question_type == "MCQ" %}
            Your answer: {{ response.selected_choice }}<br>
            {% if response.selected_choice == question.correct_answer %}
              <span style="color:green;">Correct</span>
            {% else %}
              <span style="color:red;">Incorrect</span>
            {% endif %}
          {% else %}
            Your answer: {{ response.answer_text }}
            {% if response.answer_text == question.answer_text %}
              <span style="color:green;">Correct</span>
            {% else %}
              <span style="color:red;">Incorrect</span>
            {% endif %}
          {% endif %}
        {% endif %}
      {% endfor %}
    </li>
  {% endfor %}
</ul>
<a href="{% url 'students:my_assignments' %}">Back to My Assignments</a>
<br>
<a href="{% url 'users:student_dashboard' %}">Student Dashboard</a>

students/templates/students/submit_assignment.html
<h2>Submit: {{ assignment.title }}</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Upload</button>
</form>

students/templates/students/take_quiz.html
<h2>{{ assignment.title }}</h2>
<form method="post">
  {% csrf_token %}
  {% for question in questions %}
    <div>
      <p>{{ forloop.counter }}. {{ question.text }}</p>
      {% if question.question_type == "MCQ" %}
       <label>
          <input type="radio" name="question_{{ question.id }}" value="A">
          {{ question.option_a }}
        </label><br>
        <label>
          <input type="radio" name="question_{{ question.id }}" value="B">
          {{ question.option_b }}
        </label><br>
        {% if question.option_c %}
          <label>
            <input type="radio" name="question_{{ question.id }}" value="C">
            {{ question.option_c }}
          </label><br>
        {% endif %}
        {% if question.option_d %}
          <label>
            <input type="radio" name="question_{{ question.id }}" value="D">
            {{ question.option_d }}
          </label><br>
        {% endif %} 
      {% elif question.question_type == "TEXT" %}
        <input type="text" name="question_{{ question.id }}">
      {% endif %}
    </div>
  {% endfor %}
  <button type="submit">Submit Quiz</button>
</form>

students/templates/students/view_grades.html
{% block content %}
<h2>My Grades</h2>

<table border="1">
  <tr>
    <th>Course</th>
    <th>Score</th>
    <th>Grade</th>
    <th>Feedback</th>
  </tr>
  {% for g in grades %}
  <tr>
    <td>{{ g.course.name }}</td>
    <td>{{ g.score }}</td>
    <td>{{ g.grade }}</td>
    <td>{{ g.feedback }}</td>
  </tr>
  {% empty %}
  <tr>
    <td colspan="4">No grades available yet.</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

students/templates/students/view_profile.html
<h2>My Profile</h2>
{% if profile.profile_picture %}
    <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" width="150" height="150">
{% endif %}
<p><b>Admission Number:</b> {{ profile.admission_number }}</p>
<p><b>Date of Birth:</b> {{ profile.date_of_birth }}</p>
<p><b>Course:</b> {{ profile.course }}</p>
<p><b>Year of Study:</b> {{ profile.year_of_study }}</p>
<p><b>Bio:</b> {{ profile.bio }}</p>
<a href="{% url 'students:edit_profile' %}">Edit Profile</a>